spring:
  # thymeleaf 配置
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # url: jdbc:mysql://192.168.0.160:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    # username: mysql
    # password: mysql
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 最大存活时间，0 表示永久存活，默认1800000（30 分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30 秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # Redis 配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间，默认 -1
        max-wait: 10000ms
        # 最大空闲连接，默认 8
        max-idle: 200
        # 最小空闲连接，默认 0
        min-idle: 5

  # 静态资源处理
  web:
    resources:
      add-mappings: true
    cache:
      cachecontrol:
        # 缓存响应时间，单位是秒
        max-age: 3600
    # 资源链
    chain:
      # 启用资源链，默认禁用
      enabled: true
      # 资源链开启缓存，默认启动
      cache: true
      # 启用压缩资源（gzip, brotli）解析，默认禁用
      compressed: true
      # 启用 h5 缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  # RabbitMQ 配置
  rabbitmq:
    # 服务器
    # 我用的是 Docker，采用了端口映射，映射到了 localhost
    host: localhost
    # 用户名（默认就是 guest）
    username: guest
    # 密码（默认就是 guest）
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认 true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认 false
        enabled: true
        # 重试时间：默认 1000ms
        initial-interval: 1000ms
        # 重试最大次数，默认 3 次
        max-attempts: 3
        # 重试最大间隔时间：默认 10000ms
        max-interval: 10000ms
        # 重试的间隔乘数。比如配 2.0，第一次等 1s，第二次等 2s，第三次等 4s
        multiplier: 1

# MyBatis Plus 配置
mybatis-plus:
  # 配置 Mapper.xml 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置 MyBatis 数据返回类型别名（默认别名是类名）
  type-aliases-package: com.exmaple.miaosha.pojo

# MyBatis SQL 打印（方法接口所在的包，不是 Mapper.xml 所在的包）
logging:
  level:
    com.example.seckill.mapper: debug
